language: node_js
node_js:
- '5'
notifications:
  slack:
    secure: sfXiUs4yYzMe4YzyHbzyTslVKo4MaXraeUMVCk31RcqCRD1pZ1ZhhSYReEbiQyBM9JA+gQ5exQE7W3q7c9ycJULWv6E3jEd2DIXQ/vh9zq1KoggrHWH2jBVIXtGmCk2mh1k/FomB2DENjT3nQ4EvGWJ4dWaVPIy1vRPYhKeCaPYBQsQrkT0597ev9XBjPdNgI9LUiLj9ABq5rKSbT1PSbThfj3XZLR9iL1mqjvwAoaqxGj0ZhXoJQW5oSxW7jWW/HnjW338FlzHSRJhMLnIFMq2IqkLcQFuQIM/PREmDT16BQMj+zmOAIyEwcVZ3vJQdlukWZWT9HzckmXKtFbmJfq1RIHY5xpZgqm6MvMg/m8E3Dg6Mirx7ZWP3dnRNvvnT3kzdqIL48KgCiERfaZhc5mclNspMCmJV5GRUI/MfnhEbvKK+bHmFCKTRFI0a0UI3qntNnFyqdt3TdEMyp4+FP1vd5qhA07vpUkcCxcSipaA1B9xWeGXyzUp7n0soVrcVrJ+lXuxMMs1WyhjT+b4vedil6VvADPQYoIZZZ/mwWfJdA6rMBuaWEbNEFoh1MfiRDEUp3RLoeyYKDCRTBagSe+MFXxPsj5F5D1QMA+7uOLptj75cxB19zSu7npBO965haA/woYoAwWffRAP/h+oaJr6bdErV2dHv5zg8b5e6oKU=
  email: false
